gateway:
  name: toystore
  namespace: api-gateway
  rootDomain: apps.ocpinfra01.csni.se
  jwt:
    issuerUrl: https://sso.intern.st1.csni.se/realms/connectivity-link
  routes:
      - name: admin
        namespace: toystore
        rateLimit:
          "post":
            rates:
            - limit: 2
              window: 30s
            counters:
            - expression: "auth.identity.username"
            when:
            - predicate: "request.method == 'GET'"
            - predicate: "request.path == '/admin/toy'"
            - predicate: "auth.identity.group == 'admin'"
          "delete":
            rates:
            - limit: 2
              window: 30s
            counters:
            - expression: "auth.identity.username"
            when:
            - predicate: "request.method == 'DELETE'"
            - predicate: "request.path == '/admin/toy'"
            - predicate: "auth.identity.group == 'admin'"
        rules:
          - matches:
            - path:
                type: Exact
                value: "/admin/toy"
              method: POST
            - path:
                type: Exact
                value: "/admin/toy"
              method: DELETE
            backendRefs:
              - name: toystore
                port: 80
      - name: toy
        namespace: toystore
        rateLimit:
          "global":
            rates:
            - limit: 6
              window: 30s
          "get-toy":
            when:
            - predicate: "request.method == 'GET'"
            - predicate: "request.path == '/toy'"
            rates:
            - limit: 5
              window: 1m
        rules:
          - matches:
            - path:
                type: PathPrefix
                value: "/toy"
              method: GET
            backendRefs:
              - name: toystore
                port: 80