{{- if .Values.gateway.jwt }}
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: {{ .Values.gateway.name }}-jwt
  namespace: {{ .Values.gateway.namespace }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.gateway.name }}
  rules:
    authentication:
      "oidc":
        jwt:
          issuerUrl: {{ .Values.gateway.jwt.issuerUrl }}
    authorization:
      "access-claims":
        opa:
          rego: |
{{ .Files.Get "files/authorino_allowed_routes.rego" | indent 12 }} 
    response:
      success:
        filters:
          "identity":
            json:
              properties:
                "userid":
                  selector: auth.identity.sub
{{- end }}