{{- range $route := .Values.gateway.routes }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $route.name }}
  namespace: {{ $.Values.gateway.namespace }}
spec:
  host: {{ $route.name }}-{{ $.Values.gateway.namespace }}.{{ $.Values.gateway.rootDomain }}
  to:
    kind: Service
    name: {{ $.Values.gateway.name }}-istio
    weight: 100
  port:
    targetPort: api
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
