{{- range $gateway := .Values.gateways }}
  {{- range $route := $gateway.routes }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $route.name }}
  namespace: {{ $gateway.namespace }}
spec:
  host: {{ $route.name }}-{{ $gateway.namespace }}.{{ $gateway.rootDomain }}
  to:
    kind: Service
    name: {{ $gateway.name }}-istio
    weight: 100
  port:
    targetPort: api
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
  {{- end }}
{{- end }}
