{{- range .Values.gateways }}
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: {{ .name }}-deny-auth
  namespace: {{ .namespace }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .name }}
  defaults:
   when:
     - predicate: "request.path != '/health'"
   rules:
    authorization:
      deny-all:
       metrics: false
       opa:
         allValues: false
         rego: allow = false
       priority: 0
    response:
      unauthorized:
        headers:
          "content-type":
            value: application/json
        body:
          value: |
            {
              "error": "Forbidden",
              "message": "Access denied by default by the gateway operator. If you are the administrator of the service, create a specific auth policy for the route."
            }
---
{{- end }}
