{{- range .Values.gateways }}
apiVersion: kuadrant.io/v1
kind: TLSPolicy
metadata:
  name: {{ .name }}-tls
  namespace: {{ .namespace }}
spec:
  targetRef:
    name: {{ .name }}
    group: gateway.networking.k8s.io
    kind: Gateway
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: self-signed
  commonName: {{ .name }}
---
{{- end }}
