apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: {{ .Values.gateway.name }}-rlp
  namespace: {{ .Values.gateway.namespace }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.gateway.name }}
  defaults:
    limits:
      "low-limit":
        rates:
        - limit: 1
          window: 10s
