kind: Secret
apiVersion: v1
metadata:
  name: wasm-plugin-pull-secret
  namespace: {{ .Values.gateway.namespace }}
data:
  .dockerconfigjson: {{ .Files.Get "files/.dockerconfigjson" | b64enc }}
type: kubernetes.io/dockerconfigjson

