{{- range $route := .Values.gateway.routes }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $route.name }}
  namespace: {{ $route.namespace }}
spec:
  parentRefs:
  - name: {{ $.Values.gateway.name }}
    namespace: {{ $.Values.gateway.namespace }}
  hostnames:
  - "{{ $route.name }}-{{ $.Values.gateway.namespace }}.{{ $.Values.gateway.rootDomain }}"
  rules:
{{ toYaml $route.rules | indent 4 }}
{{- end }}
