{{- range $gateway := .Values.gateways }}
  {{- range $route := $gateway.routes }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $route.name }}
  namespace: {{ $route.namespace }}
spec:
  parentRefs:
  - name: {{ $gateway.name }}
    namespace: {{ $gateway.namespace }}
  hostnames:
  - "{{ $route.name }}-{{ $gateway.namespace }}.{{ $gateway.rootDomain }}"
  rules:
{{ toYaml $route.rules | indent 4 }}
---
  {{- end }}
{{- end }}
