{{- range $route := .Values.gateway.routes }}
  {{- if $route.rateLimit }}
---
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: {{ $route.name }}-ratelimit
  namespace: {{ $route.namespace | default $.Values.gateway.namespace }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ $route.name }}
  limits:
{{ toYaml $route.rateLimit | indent 4 }}
  {{- end }}
{{- end }}